version: "3"
services:
  web:
    image: friendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:80"
    networks:
      - webnet
networks:
  webnet:
